### ISSUE TITLE
Demo Ehttp on Mobile: JsValue Error. Failed to fetch.

### ISSUE THREAD

**Issue by robertpauson** [emilk/ehttp#20]
Long await and then 
![Screenshot_2023-01-04_19-50-14](https://user-images.githubusercontent.com/114532210/210627988-d81af022-6b66-40ca-8ea4-8447e6b7319f.png)

ScreenCast:

https://user-images.githubusercontent.com/114532210/210627851-86dc5dde-af6e-4c99-b476-8dc8a28f4f4e.mp4

On Chrome same thing, but took longer.

Will it be solved? It can hang entire WASM apps.

**Comment by emilk** [comment]
It works on Safari on my iPhone.

> Will it be solved? It can hang entire WASM apps.

I think you'll need to dig into this youself, since you can reproduce it.

The whole code is extremely short and simple: https://github.com/emilk/ehttp/blob/master/ehttp/src/web.rs

**Comment by emilk** [comment]
Error message was improved in https://github.com/emilk/ehttp/pull/33
