### ISSUE TITLE
Fetching using channels

### ISSUE THREAD

**Issue by EvoTeamDevelop** [emilk/ehttp#22]
Currently I am trying to use channels receiver for wasm runtime:

```
let (sender, receiver) = mpsc::channel();

ehttp::fetch(ehttp::Request::get(&url), move |response: ehttp::Result<ehttp::Response>| {
    let result = response.unwrap();

    sender.send(result);
});
...
let response = receiver.recv().unwrap();
```

But it fails with error - panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/locks/condvar.rs:20:9:
<img width="559" alt="Screenshot 2023-02-28 at 16 45 47" src="https://user-images.githubusercontent.com/89959159/221888104-92394cff-d78c-4610-887c-63723e731c2e.png">

As I get it from other internet resources that it is not possible to use channels in wasm.
Can you please confirm that it is an issue or share an example how it is possible to fetch using channels?

**Comment by emilk** [comment]
You can use channels, you just can't block on them. Use `try_recv` instead.
