### ISSUE TITLE
Old version of rust specified

### ISSUE THREAD

**Issue by c-git** [emilk/ehttp#24]
Hi,

Thanks for making this library, it makes a lot of sense and simplifies the code using it that would need to work across both native and wasm. I want to use reqwest for my use case so going to do something similar built on reqwest instead. In doing that I was looking at this library and realized that version 1.61 of rust is specified in the [rust-toolchain](https://github.com/emilk/ehttp/blob/7c96367fea07cfa971e81889fa5b11fc9553e093/rust-toolchain#L8) file. One of the dependencies bumped their MSRV and as a result rust-analyzer gives and error when I open the workspace in VS Code. See error below:

```
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: package `raw-window-handle v0.5.2` cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.61.0


[ERROR flycheck] Flycheck failed to run the following command: cd "/home/one/ehttp" && "cargo" "clippy" "--workspace" "--message-format=json-diagnostic-rendered-ansi" "--manifest-path" "/home/one/ehttp/Cargo.toml" "--all-targets"
[ERROR rust_analyzer::lsp_utils] cargo check failed:
Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
error: package `raw-window-handle v0.5.2` cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.61.0

```

**Comment by emilk** [comment]
Oh that's annoying 🤦 I guess I could check in a `Cargo.lock` file to fix that

**Comment by emilk** [comment]
Cargo.lock is now checked in
