### ISSUE TITLE
0.3.1 tag is missing

### ISSUE THREAD

**Issue by jbeich** [emilk/ehttp#36]
According to crates.io `.cargo_vcs_info.json` from [0.3.1](https://crates.io/crates/ehttp/0.3.1) ([download](https://crates.io/api/v1/crates/ehttp/0.3.1/download))  references 39d22d298a759dd2861e5ce10a2084b7a55f78fe which doesn't exist yet in this repo.

**Comment by jbeich** [comment]
For example, the mysterious 0.3.1 (unlike 0.3.0 or HEAD at b5e2da0d9c57) fails to build:
```rust
$ rustc -vV
rustc 1.72.0 (5680fa18f 2023-08-23) (built from a source tarball)
binary: rustc
commit-hash: 5680fa18feaa87f3ff04063800aec256c3d4b4be
commit-date: 2023-08-23
host: x86_64-unknown-freebsd
release: 1.72.0
LLVM version: 16.0.5

$ cargo build
[...]
error: Could not find documented features in Cargo.toml
  --> src/lib.rs:21:10
   |
21 | #![doc = document_features::document_features!()]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `document_features::document_features` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by jbeich** [comment]
Nevermind build failure. Seems to be a downstream issue.

**Comment by emilk** [comment]
Thanks - I forgot to hit `git push` 🤦 
Fixed now
