### ISSUE TITLE
ehttp is not passing the `console` feature to `web-sys`

### ISSUE THREAD

**Issue by kekonn** [emilk/ehttp#40]
I have a library crate to which I'm trying to add unit tests. The crate builds just fine using trunk and runs when used in a project, but when I try to build the tests (`cargo build --tests --target wasm32-unknown-unknown`) I get the following error:

```
  --> C:\Users\jonas.vanderaa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ehttp-0.3.1\src\web.rs:34:22
   |
34 |             web_sys::console::error_1(&value);
   |                      ^^^^^^^ could not find `console` in `web_sys`
```

Any idea what's causing this?

**Comment by emilk** [comment]
I think `"console"` is missing from the `web-sys` features of ehttp:

https://github.com/emilk/ehttp/blob/b5e2da0d9c57ee92a9b8db5e8a2a3f38652aba52/ehttp/Cargo.toml#L52-L61
