### ISSUE TITLE
Windows Defender on Windows 10 thinks cross-compiled example_eframe is malware

### ISSUE THREAD

**Issue by rustrust** [emilk/ehttp#41]
I used https://github.com/rust-cross/cargo-xwin to cross compile the example_eframe on macOS to windows and attempted to run on windows 10. Windows Defender thinks this is Win32/Wacatac.H!ml

**Comment by dbalsom** [comment]
Not sure why you closed this, but I am having the same issue.   Did you resolve it somehow? I purchased a code signing cert, it did not help.
